<a href='[field:url/]'>[field:linename/]</a>

					<div class="pic">
						<a href="[field:url/]" target="_blank"><img src="[field:bigpic/]" /></a>
						<span><a href="[field:url/]" target="_blank">[field:linename/]</a></span>
					</div>
					
					<div class="sa_txt">
						[field:sellpoint/]	
					</div>
					
					<dl class="sa_buy">
						<dt><span>[field:lineprice/]元</span><em>/人</em></dt>	
						<dd><a href="[field:url/]" target="_blank" class="buy">立即购买 </a></dd>
					</dl>