<tr>
						<td>
							<span class="txt" id="nameval[field:id/]">[field:name/]</span>
							<input type="text" name="name" id ="name[field:id/]" class="tval" value="[field:name/]" />	
						</td>	
						<td>
							<span class="txt" id="mobileval[field:id/]">[field:mobile/]</span>
							<input type="text" name="mobile" id="mobile[field:id/]" class="tval" value="[field:mobile/]" />	
						</td>						
						<td>
							<span class="txt" id="emailval[field:id/]">[field:email/]</span>
							<input type="text" name="email" id="email[field:id/]" class="tval" value="[field:email/]" />	
                                                </td>
                                                <td>
							<span class="txt" id="idnoeval[field:id/]">[field:idno/]</span>
							<input type="text" name="idno" id="idno[field:id/]" class="tval" value="[field:idno/]" />	
						</td>						
						<td>
							<span class="txt" id="ppnoeval[field:id/]">[field:ppno/]</span>
							<input type="text" name="ppno" id="ppno[field:id/]" class="tval" value="[field:ppno/]" />	
                                                </td>
						<td class="tab_mof">
							<a href="javascript:;" class="edit_a">编辑</a>
							<a href="#" class="save_a" data="[field:id/]">保存</a>
							<a href="#" class="esc_a">取消</a>
						</td>
						<td></td>
					</tr>