<tr>
                                            <td height="50" align="right"><span class="title">验证码：</span></td>
                                            <td height="50" align="left"><input type="text" name="checkcode" id="e_checkcode" class="text length"><span class="yzm_num"><img class="yz_img" id="email_checkcode" src="" style="cursor:pointer" title="点击我更换图片" alt="点击我更换图片"></span></td>
                                            <td height="50" align="left" class="hint"><span class="hint-sub"></span>看不清楚？<a class="yaz_chenk" href="javascript:;">换一张</a><span class="reg_tip"></span><span class="error"></span></td>
                                        </tr>